apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: openshift-tasks
  name: openshift-tasks
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-tasks:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/ajosassignment/openshift-tasks   #https://github.com/OpenShiftDemos/openshift-tasks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap70-openshift:1.6
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: mysecret101
    type: GitHub
  - generic:
      secret: mysecret101
    type: Generic
  - type: ImageChange
